#!/usr/bin/env bash
# ---------------------------------------------------------------------
# Extract the functions-under-test VERBATIM from the current committed
# source and emit them wrapped in `namespace ts { ... }` on stdout.
#
# The point: we compile the ACTUAL topology_spr / collect_edges_* the
# release ships, pulled fresh from `git show HEAD:src/ts_constraint.cpp`
# on every build.  There is no hand-copied second version to drift.
# If a signature ever changes, the sed range yields nothing and we abort
# loudly (that is the correct failure — re-verify the harness).
#
# Each target function opens with its signature at column 0 and closes
# with a lone `}` at column 0 (inner braces are indented), so a
# signature-anchored `sed '/^sig/,/^}/p'` captures exactly one function,
# multi-line signatures included.
# ---------------------------------------------------------------------
set -euo pipefail

ROOT="${1:?usage: extract_funcs.sh <repo-root>}"
FILE="src/ts_constraint.cpp"

src() { git -C "$ROOT" show "HEAD:$FILE"; }

extract() { # $1 = signature anchor regex
  local body
  body="$(src | sed -n "/$1/,/^}/p")"
  if [ -z "$body" ] || [ "$(printf '%s\n' "$body" | tail -n1)" != "}" ]; then
    echo "extract_funcs.sh: FAILED to extract '$1' from HEAD:$FILE" >&2
    echo "  (signature drifted? re-verify the harness against current source)" >&2
    exit 3
  fi
  printf '%s\n' "$body"
}

cat <<'HDR'
// ============================================================
// AUTO-GENERATED by extract_funcs.sh — DO NOT EDIT.
// Verbatim copy of the functions-under-test from
//   git show HEAD:src/ts_constraint.cpp
// Regenerated on every build, so it cannot drift from the code
// the release ships.  See README.md.
// ============================================================
#include <vector>
#include <utility>
#include <cstdint>
#include "ts_tree.h"
namespace ts {
HDR

# The mutator under test and the two target-source functions:
extract '^void topology_spr('
echo
extract '^void collect_edges_in_subtree('
echo
extract '^void collect_edges_outside_subtree('
echo
# Also verbatim: the two functions that the faithful (Pass C) enumeration
# needs to reproduce the exact emission set — per-node tip bitmasks and the
# mask-restricted maximal-subtree finder that yields move_out/in_roots.
extract '^std::vector<uint64_t> compute_node_tips('
echo
extract '^void find_maximal_subtrees('

echo "} // namespace ts"
