cat("Loading...\n")
devtools::load_all(quiet = TRUE, compile = FALSE)
library(TreeTools)

cat("Creating dataset...\n")
dataset <- TreeTools::StringToPhyDat("110000 111000 111100", 1:6, byTaxon = FALSE)

cat("Test 1: Simple balanced tree\n")
tree1 <- ape::read.tree(text = "(((((1,2),3),4),5),6);")
cat("Calculating TreeLength...\n")
flush.console()
result1 <- TreeLength(tree1, dataset)
cat("Result:", result1, "\n")

cat("\nTest 2: Another tree\n")
tree2 <- ape::read.tree(text = "(((1, 6), 3), (2, (4, 5)));")
cat("Tree2 tip.label:", tree2$tip.label, "\n")
cat("Dataset names:", names(dataset), "\n")
tree2 <- RenumberTips(tree2, names(dataset))
cat("Calculating TreeLength...\n")
flush.console()
result2 <- TreeLength(tree2, dataset)
cat("Result:", result2, "\n")
