context("pp_exact")

# TODO this test was recovered from a stash and requires updating -- 
# or may be obselete.
test_that("Profile score correct for small trees", {
  library("TreeTools", quietly = TRUE, warn.conflicts = FALSE)
  tree <- as.phylo(200, 9)
  
  mataset <- matrix(c(
    1, 1, 1, 1, 0, 0, 0, 0, 0, # 3 steps
    1, 0, 0, 1, 0, 0, 1, 0, 0, # 2 steps
    1, 0, 0, 1, 0, 0, 1, 0, 0, # duplicated
    0, 1, 0, 0, 0, 0, 0, 1, 1, # 1 step
    2, 1, 1, 1, 1, 1, 1, 1, 1),# 1 step; non-informative
    nrow = 9, dimnames = list(paste0('t', 1:9), NULL))
    
  
  dataset <- MatrixToPhyDat(mataset)
  
  at <- attributes(dataset)
  characters <- PhyToString(dataset, ps = '', useIndex = FALSE,
                            byTaxon = FALSE, concatenate = FALSE)
  weight <- at$weight
  morphyObjects <- lapply(characters, SingleCharMorphy)
  on.exit(morphyObjects <- vapply(morphyObjects, UnloadMorphy, integer(1)))
  
  nLevel <- length(at$level)
  nChar <- at$nr
  cont <- at$contrast
  simpleCont <- ifelse(rowSums(cont) == 1,
                       apply(cont != 0, 1, function (x) at$levels[x][1]),
                       '?')
  inappLevel <- at$levels == '-'
  
  unlisted <- unlist(dataset, use.names = FALSE)
  charSeq <- seq_len(nChar) - 1L
  
  
  tokenMatrix <- matrix(simpleCont[unlisted], nChar, 9, byrow = FALSE)
  profileTables <- apply(tokenMatrix, 1, table)
  if (inherits(profileTables, 'matrix')) {
    profileTables <- lapply(seq_len(ncol(profileTables)), function (i) profileTables[, i])
  }
  data('profiles', package = 'TreeSearch')
  profileCost <- lapply(profileTables, function (x) {
    x <- sort(x[x > 1])
    n <- length(x)
    prof <- switch(n,
                   0,
                   profiles[[sum(x)]][[n]][[x[1] - 1L]]
    )
  })
  profileExtra <- lapply(profileCost, function (x)  x - x[1])
  fixedCost <- -sum(vapply(profileCost, `[[`, 1, 1) * weight)
  maxScore <- sum(Log2Unrooted(vapply(profileTables, sum, 1)))
  
  PP <- function (costs) {
    TreeSearch:::morphy_profile(edge, morphyObjects, weight, costs, charSeq, Inf)
  }
  
  edge <- tree$edge
  
  extraSteps <- lapply(profileTables, function (x) 1:9)
  
  expect_equal(Fitch(tree, dataset), PP(costs = extraSteps))
  # 3 + 2 + 2 + 1 + 1
  message(Fitch(tree, dataset))
  
  expect_equal(sum(profileExtra[[1]][3], 2 * profileExtra[[2]][2]),
               PP(costs = profileExtra))
  
  morphyObjects <- vapply(morphyObjects, UnloadMorphy, integer(1))
})


context("pp_ProfileScore.R")
test_that("Profile score calculated correctly", {
  data(referenceTree)
  data(congreveLamsdellMatrices)
  tree <- referenceTree
  suppressWarnings(RNGversion("3.5.0")) # Until we can require R3.6.0
  set.seed(0)
  dataset <- PrepareDataProfile(congreveLamsdellMatrices[[1]], 4e+04, warn=FALSE)
  expect_equal(TreeLength(tree, dataset), 
               sum(CharacterLength(tree, dataset) * attr(dataset, 'weight')))
  score <- ProfileScore(tree, dataset)
  expect_true(abs(354.58 + score) < 9) # Range as concavity constants generated by approximation
})
