app <- ShinyDriver$new("../../", seed = 0, loadTimeout = 2e+05,
                       shinyOptions = list(test.mode = TRUE))
app$snapshotInit("Distribution")

app$setInputs(dataSource = "Sun2018")
app$setInputs(plotFormat = "clus")
app$snapshot()
app$setInputs(clThresh = 1)
app$setInputs(consP = 0.5)
app$snapshot()
app$setInputs(concordance = "qc")
app$snapshot()
app$setInputs(plotFormat = "ind", timeout_ = 6000)
app$setInputs(concordance = "clc")
app$snapshot()
app$setInputs(plotFormat = "space")
app$snapshot()
app$setInputs(clThresh = 0.5)
app$snapshot()
app$setInputs(plotSize = 400)
app$setInputs(spaceCol = "score")
app$setInputs(spaceDim = 3)
app$setInputs(plotFormat = "space")
app$setInputs(relators = c("Wiwaxia_corrugata", "Tonicella", "Dentalium", "Phoronis"))
app$snapshot()
app$setInputs(spaceCol = "firstHit")
app$setInputs(spaceCol = "score")
app$setInputs(distMeth = "pid")
app$snapshot()
app$setInputs(distMeth = "rf")
app$snapshot()
app$setInputs(dataSource = "Agnarsson2004")
app$setInputs(distMeth = "qd")
app$snapshot()
