app <- ShinyDriver$new("../../", seed = 0, loadTimeout = 2e+05,
                       shinyOptions = list(test.mode = TRUE))
app$snapshotInit("Distribution")
# Test downloaded logs with
# source("inst/parsimony/tests/shinytest/Distribution-current/002.download")

app$setInputs(dataSource = "Sun2018")
app$setInputs(plotFormat = "clus")
app$setInputs(treeRange = c(77, 125))
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(nTree = 125)
app$setInputs(treeRange = c(1, 125))
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(clThresh = 1)
app$setInputs(consP = 0.5)
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(concordance = "qc")
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(concordance = "clc", timeout_ = 6000)
app$setInputs(plotFormat = "ind", timeout_ = 6000)
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(plotFormat = "space")
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(clThresh = 0.5)
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(plotSize = 400)
app$setInputs(spaceCol = "score")
app$setInputs(spaceDim = 3)
app$setInputs(plotFormat = "space")
app$setInputs(mapLines = "seq")
app$setInputs(relators = c("Wiwaxia_corrugata", "Tonicella", "Dentalium", "Phoronis"))
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(mapLines = character(0))
app$setInputs(spaceCol = "firstHit")
app$setInputs(spaceCol = "score")
app$setInputs(distMeth = "pid")
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(distMeth = "rf")
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(dataSource = "Agnarsson2004")
app$setInputs(distMeth = "qd")
app$snapshot()
app$snapshotDownload("savePlotZip")
