app <- ShinyDriver$new("../../", seed = 0, loadTimeout = 2e+05,
                       shinyOptions = list(test.mode = TRUE))
app$snapshotInit("ViewChars")
# Test downloaded logs with
# source("inst/parsimony/tests/shinytest/viewchars-current/002.download")

app$uploadFile(dataFile = "../../../datasets/Agnarsson2004.nex")
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(consP = 0.5)
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(neverDrop = "Argiope") # Avoid resetting root
app$setInputs(keepNTips = 1)
app$setInputs(keepNTips = 2)
app$snapshot() # Check for correct display of invalid input: no log needed
app$setInputs(keepNTips = 61)
app$setInputs(outgroup = "Argiope",
              timeout_ = 5000) # Ensure not modified by dropping tips
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(keepNTips = 59) # Check tips kept legend changes to 17
app$setInputs(excludedTip = "Emertonella", timeout_ = 2e05)
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(neverDrop = "Emertonella") 
# QuickRogue triggered; keepNTips will change to 61
app$setInputs(keepNTips = 59)
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(outgroup = character(0))
app$setInputs(outgroup = "Thymoites")
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(plotFormat = "ind")
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(plottedChar = 0)
app$setInputs(mapDisplay = "tipsRight")
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(mapDisplay = character(0))
app$setInputs(plottedChar = 1)
app$setInputs(plottedChar = 2)
app$setInputs(plottedChar = 3)
app$setInputs(plottedChar = 6)
app$setInputs(plottedChar = 7)
app$setInputs(plottedChar = 8)
app$setInputs(plottedChar = 7)
app$snapshot()
app$snapshotDownload("savePlotZip")
app$setInputs(plottedChar = 8)
app$setInputs(plottedChar = 11)
app$setInputs(plottedChar = 53)
app$setInputs(whichTree = 7)
app$snapshot()
app$snapshotDownload("savePlotZip")
