app <- ShinyDriver$new("../../", seed = 0, loadTimeout = 2e+05,
                       shinyOptions = list(test.mode = TRUE))
app$snapshotInit("ViewChars")

app$setInputs(dataSource = "Agnarsson2004")
app$snapshot()
app$setInputs(consP = 0.5)
app$snapshot()
app$setInputs(keepTips = 61)
app$snapshot()
app$setInputs(keepTips = 59) # Check tips kept legend changes to 17
app$setInputs(excludedTip = "Emertonella", timeout_  =2e05)
app$snapshot()
app$setInputs(neverDrop = "Emertonella")
app$snapshot()
app$setInputs(outgroup = character(0))
app$setInputs(outgroup = "Thymoites")
app$snapshot()
app$setInputs(plotFormat = "ind")
app$snapshot()
app$setInputs(whichChar = 0)
app$setInputs(mapDisplay = "tipsRight")
app$snapshot()
app$setInputs(mapDisplay = character(0))
app$setInputs(whichChar = 1)
app$setInputs(whichChar = 2)
app$setInputs(whichChar = 3)
app$setInputs(whichChar = 6)
app$setInputs(whichChar = 7)
app$setInputs(whichChar = 8)
app$setInputs(whichChar = 7)
app$snapshot()
app$setInputs(whichChar = 8)
app$setInputs(whichChar = 11)
app$setInputs(whichChar = 53)
app$setInputs(whichTree = 7)
app$snapshot()
