// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nni
IntegerMatrix nni(const IntegerMatrix edge, const IntegerVector randomEdge, const IntegerVector whichSwitch);
RcppExport SEXP _TreeSearch_nni(SEXP edgeSEXP, SEXP randomEdgeSEXP, SEXP whichSwitchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type randomEdge(randomEdgeSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type whichSwitch(whichSwitchSEXP);
    rcpp_result_gen = Rcpp::wrap(nni(edge, randomEdge, whichSwitch));
    return rcpp_result_gen;
END_RCPP
}
// root_on_node
IntegerMatrix root_on_node(const IntegerMatrix edge, int outgroup);
RcppExport SEXP _TreeSearch_root_on_node(SEXP edgeSEXP, SEXP outgroupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type outgroup(outgroupSEXP);
    rcpp_result_gen = Rcpp::wrap(root_on_node(edge, outgroup));
    return rcpp_result_gen;
END_RCPP
}
// spr_moves
IntegerMatrix spr_moves(const IntegerMatrix edge);
RcppExport SEXP _TreeSearch_spr_moves(SEXP edgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type edge(edgeSEXP);
    rcpp_result_gen = Rcpp::wrap(spr_moves(edge));
    return rcpp_result_gen;
END_RCPP
}
// spr
IntegerMatrix spr(const IntegerMatrix edge, const IntegerVector move_id);
RcppExport SEXP _TreeSearch_spr(SEXP edgeSEXP, SEXP move_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type move_id(move_idSEXP);
    rcpp_result_gen = Rcpp::wrap(spr(edge, move_id));
    return rcpp_result_gen;
END_RCPP
}
