// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nni
IntegerMatrix nni(IntegerMatrix edge, IntegerVector randomEdge, IntegerVector whichSwitch);
RcppExport SEXP _TreeSearch_nni(SEXP edgeSEXP, SEXP randomEdgeSEXP, SEXP whichSwitchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type randomEdge(randomEdgeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type whichSwitch(whichSwitchSEXP);
    rcpp_result_gen = Rcpp::wrap(nni(edge, randomEdge, whichSwitch));
    return rcpp_result_gen;
END_RCPP
}
