# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nni <- function(edge, randomEdge, whichSwitch) {
    .Call(`_TreeSearch_nni`, edge, randomEdge, whichSwitch)
}

root_on_node <- function(edge, outgroup) {
    .Call(`_TreeSearch_root_on_node`, edge, outgroup)
}

spr_moves <- function(edge) {
    .Call(`_TreeSearch_spr_moves`, edge)
}

spr <- function(edge, move) {
    .Call(`_TreeSearch_spr`, edge, move)
}

