on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**/**.yml"
      - "!**coverage.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**/**.yml"
      - "!**coverage.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"

name: Code coverage

jobs:
  R-CMD-check:
    runs-on: ubuntu-20.04

    name: Code coverage

    env:
      _R_CHECK_CRAN_INCOMING_: true # Seemingly not set by --as-cran
      _R_CHECK_FORCE_SUGGESTS_: false # CRAN settings
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: |
            coverage

      - name: Code coverage
        if: runner.os == 'Windows'
        run: |
          covr::codecov()
        shell: Rscript {0}
